Traceback (most recent call last):
  File "/home/shz19039/sasp/tune_v1.py", line 159, in <module>
    main(alpha=args.alpha, seed=args.seed, prefix=args.prefix)
  File "/home/shz19039/sasp/tune_v1.py", line 96, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_a005_s1.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 98, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 69, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s1.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 122, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 72, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s1.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/tune_v1.py", line 159, in <module>
    main(alpha=args.alpha, seed=args.seed, prefix=args.prefix)
  File "/home/shz19039/sasp/tune_v1.py", line 96, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_a005_s2.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 98, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 69, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s2.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 122, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 72, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s2.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/tune_v1.py", line 159, in <module>
    main(alpha=args.alpha, seed=args.seed, prefix=args.prefix)
  File "/home/shz19039/sasp/tune_v1.py", line 96, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_a005_s3.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 98, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 69, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s3.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 122, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 72, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s3.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/tune_v1.py", line 159, in <module>
    main(alpha=args.alpha, seed=args.seed, prefix=args.prefix)
  File "/home/shz19039/sasp/tune_v1.py", line 96, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_a005_s4.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 98, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 69, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s4.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 122, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 72, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s4.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/tune_v1.py", line 159, in <module>
    main(alpha=args.alpha, seed=args.seed, prefix=args.prefix)
  File "/home/shz19039/sasp/tune_v1.py", line 96, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_a005_s5.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 98, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_ukb.py", line 69, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s5.pth'
Traceback (most recent call last):
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 122, in <module>
    main( prefix=args.prefix, alpha=args.alpha, seed=args.seed)
  File "/home/shz19039/sasp/encode_sasp_medex.py", line 72, in main
    tgae.load_state_dict(torch.load(model_path))
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shz19039/miniconda3/envs/climate/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gae_t1_a005_s5.pth'
